# Generated by Django 5.2.1 on 2025-05-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPTfinal', '0002_reservation_room_notification_reservation_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(choices=[('Room A', 'Room A'), ('Room B', 'Room B'), ('Room C', 'Room C'), ('Room D', 'Room D')], max_length=100),
        ),
    ]
